package operator_test

import (
	"context"
	"log/slog"
	"os"
	"testing"

	"golang.org/x/crypto/bcrypt"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"

	pgmqttv1alpha1 "github.com/bo0tzz/pgmqtt/api/v1alpha1"
	"github.com/bo0tzz/pgmqtt/internal/db/dbtest"
	"github.com/bo0tzz/pgmqtt/internal/operator"
)

func newScheme(t *testing.T) *runtime.Scheme {
	t.Helper()
	s := runtime.NewScheme()
	if err := pgmqttv1alpha1.AddToScheme(s); err != nil {
		t.Fatalf("add: %v", err)
	}
	if err := corev1.AddToScheme(s); err != nil {
		t.Fatalf("add core: %v", err)
	}
	return s
}

func TestReconcile_AutoGeneratedSecret(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)

	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "ha", Namespace: "mqtt"},
	}
	cli := fake.NewClientBuilder().
		WithScheme(scheme).
		WithObjects(user).
		WithStatusSubresource(&pgmqttv1alpha1.User{}).
		Build()

	r := &operator.UserReconciler{
		Client:      cli,
		Scheme:      scheme,
		Pool:        pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt.mqtt.svc.cluster.local",
		ServicePort: 1883,
		WSPort:      8083,
	}

	// First reconcile adds the finalizer and requeues.
	res, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "ha"}})
	if err != nil {
		t.Fatalf("reconcile 1: %v", err)
	}
	if !res.Requeue {
		t.Fatalf("expected requeue after finalizer add")
	}

	// Second reconcile generates the Secret and upserts users.
	if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "ha"}}); err != nil {
		t.Fatalf("reconcile 2: %v", err)
	}

	var sec corev1.Secret
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "ha-mqtt-credentials"}, &sec); err != nil {
		t.Fatalf("get secret: %v", err)
	}
	if string(sec.Data["username"]) != "ha" {
		t.Errorf("username: %q", sec.Data["username"])
	}
	if len(sec.Data["password"]) == 0 {
		t.Error("password missing")
	}
	if string(sec.Data["host"]) != "pgmqtt.mqtt.svc.cluster.local" {
		t.Errorf("host: %q", sec.Data["host"])
	}
	if string(sec.Data["uri"]) == "" {
		t.Error("uri missing")
	}

	// users row exists with bcrypt of the generated password.
	var hash string
	if err := pool.QueryRow(context.Background(),
		`SELECT password_hash FROM users WHERE username='ha'`).Scan(&hash); err != nil {
		t.Fatalf("query: %v", err)
	}
	if err := bcrypt.CompareHashAndPassword([]byte(hash), sec.Data["password"]); err != nil {
		t.Errorf("password mismatch: %v", err)
	}

	// Owner reference on Secret.
	if len(sec.OwnerReferences) != 1 || sec.OwnerReferences[0].Name != "ha" {
		t.Errorf("owner refs: %+v", sec.OwnerReferences)
	}
}

func TestReconcile_BYOSecret(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)

	byoSec := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{Name: "ha-byo", Namespace: "mqtt"},
		Data:       map[string][]byte{"password": []byte("hunter2")},
	}
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "ha", Namespace: "mqtt"},
		Spec: pgmqttv1alpha1.UserSpec{
			Username: "homeassistant",
			PasswordSecretRef: &corev1.SecretKeySelector{
				LocalObjectReference: corev1.LocalObjectReference{Name: "ha-byo"},
				Key:                  "password",
			},
		},
	}
	cli := fake.NewClientBuilder().
		WithScheme(scheme).
		WithObjects(user, byoSec).
		WithStatusSubresource(&pgmqttv1alpha1.User{}).
		Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}

	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "ha"}}); err != nil {
			t.Fatalf("reconcile %d: %v", i, err)
		}
	}

	var hash string
	if err := pool.QueryRow(context.Background(),
		`SELECT password_hash FROM users WHERE username='homeassistant'`).Scan(&hash); err != nil {
		t.Fatalf("query: %v", err)
	}
	if err := bcrypt.CompareHashAndPassword([]byte(hash), []byte("hunter2")); err != nil {
		t.Errorf("password mismatch: %v", err)
	}

	// No auto-generated secret exists.
	var auto corev1.Secret
	err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "ha-mqtt-credentials"}, &auto)
	if err == nil {
		t.Error("auto-generated secret should not exist for BYO")
	}
}

func TestReconcile_DeletionRemovesUser(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "to-be-deleted", Namespace: "mqtt"},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}

	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "to-be-deleted"}}); err != nil {
			t.Fatalf("reconcile: %v", err)
		}
	}

	if err := cli.Delete(context.Background(), user); err != nil {
		t.Fatalf("delete: %v", err)
	}
	if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "to-be-deleted"}}); err != nil {
		t.Fatalf("reconcile delete: %v", err)
	}

	var n int
	if err := pool.QueryRow(context.Background(),
		`SELECT count(*) FROM users WHERE username='to-be-deleted'`).Scan(&n); err != nil {
		t.Fatalf("query: %v", err)
	}
	if n != 0 {
		t.Errorf("user still in DB: %d rows", n)
	}
}
