package operator_test

import (
	"context"
	"errors"
	"log/slog"
	"os"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5/pgxpool"
	"golang.org/x/crypto/bcrypt"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	"sigs.k8s.io/controller-runtime/pkg/client/interceptor"

	pgmqttv1alpha1 "github.com/bo0tzz/pgmqtt/api/v1alpha1"
	"github.com/bo0tzz/pgmqtt/internal/db/dbtest"
	"github.com/bo0tzz/pgmqtt/internal/operator"
)

func newScheme(t *testing.T) *runtime.Scheme {
	t.Helper()
	s := runtime.NewScheme()
	if err := pgmqttv1alpha1.AddToScheme(s); err != nil {
		t.Fatalf("add: %v", err)
	}
	if err := corev1.AddToScheme(s); err != nil {
		t.Fatalf("add core: %v", err)
	}
	return s
}

func TestReconcile_AutoGeneratedSecret(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)

	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "ha", Namespace: "mqtt"},
	}
	cli := fake.NewClientBuilder().
		WithScheme(scheme).
		WithObjects(user).
		WithStatusSubresource(&pgmqttv1alpha1.User{}).
		Build()

	r := &operator.UserReconciler{
		Client:      cli,
		Scheme:      scheme,
		Pool:        pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt.mqtt.svc.cluster.local",
		ServicePort: 1883,
		WSPort:      8083,
	}

	// First reconcile adds the finalizer and requeues.
	res, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "ha"}})
	if err != nil {
		t.Fatalf("reconcile 1: %v", err)
	}
	if !res.Requeue {
		t.Fatalf("expected requeue after finalizer add")
	}

	// Second reconcile generates the Secret and upserts users.
	if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "ha"}}); err != nil {
		t.Fatalf("reconcile 2: %v", err)
	}

	var sec corev1.Secret
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "ha-mqtt-credentials"}, &sec); err != nil {
		t.Fatalf("get secret: %v", err)
	}
	if string(sec.Data["username"]) != "ha" {
		t.Errorf("username: %q", sec.Data["username"])
	}
	if len(sec.Data["password"]) == 0 {
		t.Error("password missing")
	}
	if string(sec.Data["host"]) != "pgmqtt.mqtt.svc.cluster.local" {
		t.Errorf("host: %q", sec.Data["host"])
	}
	if string(sec.Data["uri"]) == "" {
		t.Error("uri missing")
	}

	// users row exists with bcrypt of the generated password.
	var hash string
	if err := pool.QueryRow(context.Background(),
		`SELECT password_hash FROM users WHERE username='ha'`).Scan(&hash); err != nil {
		t.Fatalf("query: %v", err)
	}
	if err := bcrypt.CompareHashAndPassword([]byte(hash), sec.Data["password"]); err != nil {
		t.Errorf("password mismatch: %v", err)
	}

	// Owner reference on Secret.
	if len(sec.OwnerReferences) != 1 || sec.OwnerReferences[0].Name != "ha" {
		t.Errorf("owner refs: %+v", sec.OwnerReferences)
	}
}

func TestReconcile_BYOSecret(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)

	byoSec := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{Name: "ha-byo", Namespace: "mqtt"},
		Data:       map[string][]byte{"password": []byte("hunter2")},
	}
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "ha", Namespace: "mqtt"},
		Spec: pgmqttv1alpha1.UserSpec{
			Username: "homeassistant",
			PasswordSecretRef: &corev1.SecretKeySelector{
				LocalObjectReference: corev1.LocalObjectReference{Name: "ha-byo"},
				Key:                  "password",
			},
		},
	}
	cli := fake.NewClientBuilder().
		WithScheme(scheme).
		WithObjects(user, byoSec).
		WithStatusSubresource(&pgmqttv1alpha1.User{}).
		Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}

	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "ha"}}); err != nil {
			t.Fatalf("reconcile %d: %v", i, err)
		}
	}

	var hash string
	if err := pool.QueryRow(context.Background(),
		`SELECT password_hash FROM users WHERE username='homeassistant'`).Scan(&hash); err != nil {
		t.Fatalf("query: %v", err)
	}
	if err := bcrypt.CompareHashAndPassword([]byte(hash), []byte("hunter2")); err != nil {
		t.Errorf("password mismatch: %v", err)
	}

	// No auto-generated secret exists.
	var auto corev1.Secret
	err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "ha-mqtt-credentials"}, &auto)
	if err == nil {
		t.Error("auto-generated secret should not exist for BYO")
	}
}

// TestReconcile_NotFound exercises the early-return path when the User CR
// has been deleted before the work item is processed (an event fired but
// the cache entry is gone). Reconcile must return cleanly with no error
// and not panic on the missing object.
func TestReconcile_NotFound(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	res, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "ghost"}})
	if err != nil {
		t.Fatalf("reconcile: %v", err)
	}
	if res.Requeue {
		t.Errorf("expected no requeue for not-found user")
	}
}

// TestReconcile_IsIdempotent verifies that reconciling an already-up-to-
// date User does not re-hash the password (which would change the stored
// bcrypt despite the cleartext being identical). The hash field's
// bcrypt-cost parameter is comparable since CompareHashAndPassword
// validates regardless; we instead snapshot the hash bytes and assert
// they don't change across redundant reconciles.
func TestReconcile_IsIdempotent(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "idem", Namespace: "mqtt"},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	// Run twice to settle finalizer + initial provision.
	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "idem"}}); err != nil {
			t.Fatalf("reconcile %d: %v", i, err)
		}
	}
	var hashBefore string
	if err := pool.QueryRow(context.Background(),
		`SELECT password_hash FROM users WHERE username='idem'`).Scan(&hashBefore); err != nil {
		t.Fatalf("query: %v", err)
	}
	// Run a third time — should be a no-op-on-DB (status update only).
	if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "idem"}}); err != nil {
		t.Fatalf("reconcile 3: %v", err)
	}
	var hashAfter string
	if err := pool.QueryRow(context.Background(),
		`SELECT password_hash FROM users WHERE username='idem'`).Scan(&hashAfter); err != nil {
		t.Fatalf("query: %v", err)
	}
	if hashBefore != hashAfter {
		t.Errorf("hash changed across idempotent reconcile:\n  before=%s\n  after =%s", hashBefore, hashAfter)
	}
}

// TestReconcile_BYOSecretCustomKey exercises the path where the User CR
// references a Secret with a non-default key for the password.
func TestReconcile_BYOSecretCustomKey(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	byoSec := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{Name: "creds", Namespace: "mqtt"},
		Data:       map[string][]byte{"my-pw-key": []byte("s3kr3t")},
	}
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "byo", Namespace: "mqtt"},
		Spec: pgmqttv1alpha1.UserSpec{
			PasswordSecretRef: &corev1.SecretKeySelector{
				LocalObjectReference: corev1.LocalObjectReference{Name: "creds"},
				Key:                  "my-pw-key",
			},
		},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user, byoSec).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "byo"}}); err != nil {
			t.Fatalf("reconcile %d: %v", i, err)
		}
	}
	var hash string
	if err := pool.QueryRow(context.Background(),
		`SELECT password_hash FROM users WHERE username='byo'`).Scan(&hash); err != nil {
		t.Fatalf("query: %v", err)
	}
	if err := bcrypt.CompareHashAndPassword([]byte(hash), []byte("s3kr3t")); err != nil {
		t.Errorf("password mismatch with custom key: %v", err)
	}
}

// TestReconcile_BcryptCostHonored asserts the BcryptCost field on the
// reconciler is used to compute the stored hash. We can't read the cost
// out of the bcrypt format directly without parsing, but the cost prefix
// is encoded as `$2a$NN$` so a simple string check works.
func TestReconcile_BcryptCostHonored(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "costy", Namespace: "mqtt"},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
		BcryptCost:  6, // explicit, non-default
	}
	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "costy"}}); err != nil {
			t.Fatalf("reconcile %d: %v", i, err)
		}
	}
	var hash string
	if err := pool.QueryRow(context.Background(),
		`SELECT password_hash FROM users WHERE username='costy'`).Scan(&hash); err != nil {
		t.Fatalf("query: %v", err)
	}
	// bcrypt golang's GenerateFromPassword writes the cost as a
	// zero-padded 2-digit decimal between dollar signs.
	if !strings.HasPrefix(hash, "$2a$06$") {
		t.Errorf("expected bcrypt cost 6 in hash prefix, got %q", hash[:7])
	}
}

func TestReconcile_DeletionRemovesUser(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "to-be-deleted", Namespace: "mqtt"},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}

	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "to-be-deleted"}}); err != nil {
			t.Fatalf("reconcile: %v", err)
		}
	}

	if err := cli.Delete(context.Background(), user); err != nil {
		t.Fatalf("delete: %v", err)
	}
	if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "to-be-deleted"}}); err != nil {
		t.Fatalf("reconcile delete: %v", err)
	}

	var n int
	if err := pool.QueryRow(context.Background(),
		`SELECT count(*) FROM users WHERE username='to-be-deleted'`).Scan(&n); err != nil {
		t.Fatalf("query: %v", err)
	}
	if n != 0 {
		t.Errorf("user still in DB: %d rows", n)
	}
}

// TestReconcile_BYOSecret_NotFound exercises the error path where
// spec.PasswordSecretRef points at a Secret that does not exist. The
// reconciler must surface the error and set Ready=False with reason
// SecretError on the User status.
func TestReconcile_BYOSecret_NotFound(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{
			Name:       "ghost-byo",
			Namespace:  "mqtt",
			Finalizers: []string{"pgmqtt.io/user"},
		},
		Spec: pgmqttv1alpha1.UserSpec{
			PasswordSecretRef: &corev1.SecretKeySelector{
				LocalObjectReference: corev1.LocalObjectReference{Name: "missing"},
				Key:                  "password",
			},
		},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}

	res, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "ghost-byo"}})
	if err == nil {
		t.Fatalf("expected error from missing BYO secret, got result %+v", res)
	}
	if !apierrors.IsNotFound(err) {
		t.Errorf("expected NotFound error, got: %v", err)
	}

	var got pgmqttv1alpha1.User
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "ghost-byo"}, &got); err != nil {
		t.Fatalf("get user: %v", err)
	}
	if !hasReadyCondition(got, metav1.ConditionFalse, "SecretError") {
		t.Errorf("expected Ready=False with reason SecretError, got conditions: %+v", got.Status.Conditions)
	}
}

// TestReconcile_BYOSecret_MissingKey exercises the error path where the
// referenced Secret exists but the named key is absent.
func TestReconcile_BYOSecret_MissingKey(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	byoSec := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{Name: "creds", Namespace: "mqtt"},
		Data:       map[string][]byte{"some-other-key": []byte("nope")},
	}
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{
			Name:       "no-key",
			Namespace:  "mqtt",
			Finalizers: []string{"pgmqtt.io/user"},
		},
		Spec: pgmqttv1alpha1.UserSpec{
			PasswordSecretRef: &corev1.SecretKeySelector{
				LocalObjectReference: corev1.LocalObjectReference{Name: "creds"},
				Key:                  "password",
			},
		},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user, byoSec).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	_, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "no-key"}})
	if err == nil {
		t.Fatal("expected error for BYO secret with missing key")
	}
	if !strings.Contains(err.Error(), "missing key") {
		t.Errorf("expected 'missing key' error, got: %v", err)
	}

	var got pgmqttv1alpha1.User
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "no-key"}, &got); err != nil {
		t.Fatalf("get user: %v", err)
	}
	if !hasReadyCondition(got, metav1.ConditionFalse, "SecretError") {
		t.Errorf("expected Ready=False with reason SecretError, got conditions: %+v", got.Status.Conditions)
	}
}

// TestReconcile_BYOSecret_DefaultKey verifies the fallback when
// spec.PasswordSecretRef.Key is empty. The reconciler uses "password" as
// the implicit key.
func TestReconcile_BYOSecret_DefaultKey(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	byoSec := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{Name: "default-key", Namespace: "mqtt"},
		Data:       map[string][]byte{"password": []byte("implicit-key")},
	}
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "byo-default", Namespace: "mqtt"},
		Spec: pgmqttv1alpha1.UserSpec{
			PasswordSecretRef: &corev1.SecretKeySelector{
				LocalObjectReference: corev1.LocalObjectReference{Name: "default-key"},
				// Key intentionally left empty; reconciler must default to "password".
			},
		},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user, byoSec).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "byo-default"}}); err != nil {
			t.Fatalf("reconcile %d: %v", i, err)
		}
	}
	var hash string
	if err := pool.QueryRow(context.Background(),
		`SELECT password_hash FROM users WHERE username='byo-default'`).Scan(&hash); err != nil {
		t.Fatalf("query: %v", err)
	}
	if err := bcrypt.CompareHashAndPassword([]byte(hash), []byte("implicit-key")); err != nil {
		t.Errorf("password mismatch with default key fallback: %v", err)
	}
}

// TestReconcile_DefaultsServiceWireDetails verifies the fallbacks when
// the reconciler's ServiceHost / ServicePort / WSPort are zero-valued.
// The auto-generated Secret should still contain valid wire fields.
func TestReconcile_DefaultsServiceWireDetails(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "defaults", Namespace: "mqtt"},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	// All wire defaults left at zero so the reconciler picks its fallbacks.
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger: slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
	}
	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "defaults"}}); err != nil {
			t.Fatalf("reconcile %d: %v", i, err)
		}
	}
	var sec corev1.Secret
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "defaults-mqtt-credentials"}, &sec); err != nil {
		t.Fatalf("get secret: %v", err)
	}
	if string(sec.Data["host"]) != "pgmqtt" {
		t.Errorf("default host: got %q, want %q", sec.Data["host"], "pgmqtt")
	}
	if string(sec.Data["port"]) != "1883" {
		t.Errorf("default port: got %q, want %q", sec.Data["port"], "1883")
	}
	if string(sec.Data["ws-port"]) != "8083" {
		t.Errorf("default ws-port: got %q, want %q", sec.Data["ws-port"], "8083")
	}
	if !strings.HasPrefix(string(sec.Data["uri"]), "mqtt://") {
		t.Errorf("uri default scheme: %q", sec.Data["uri"])
	}
	if !strings.HasPrefix(string(sec.Data["ws-uri"]), "ws://") {
		t.Errorf("ws-uri default scheme: %q", sec.Data["ws-uri"])
	}
}

// TestReconcile_AutoGenSecretPasswordPreservedAcrossReconciles verifies
// the existing-secret branch in resolveCredentialSecret: when the
// auto-generated Secret already exists, its password must be reused —
// not replaced with a fresh random one. This protects clients that have
// already cached the value.
func TestReconcile_AutoGenSecretPasswordPreservedAcrossReconciles(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "preserve", Namespace: "mqtt"},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "preserve"}}); err != nil {
			t.Fatalf("reconcile %d: %v", i, err)
		}
	}
	var sec1 corev1.Secret
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "preserve-mqtt-credentials"}, &sec1); err != nil {
		t.Fatalf("get secret: %v", err)
	}
	pwBefore := string(sec1.Data["password"])
	if pwBefore == "" {
		t.Fatal("first-pass password is empty")
	}

	// Wipe the observed-hash status so the reconciler is forced through the
	// existing-secret password-preservation branch on the next pass.
	var u pgmqttv1alpha1.User
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "preserve"}, &u); err != nil {
		t.Fatalf("get user: %v", err)
	}
	u.Status.ObservedSecretHash = ""
	u.Status.CredentialsSecretRef = nil
	if err := cli.Status().Update(context.Background(), &u); err != nil {
		t.Fatalf("status update: %v", err)
	}

	// Reconcile again — must reuse the existing Secret's password rather
	// than rolling a fresh random one.
	if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "preserve"}}); err != nil {
		t.Fatalf("reconcile rerun: %v", err)
	}
	var sec2 corev1.Secret
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "preserve-mqtt-credentials"}, &sec2); err != nil {
		t.Fatalf("get secret 2: %v", err)
	}
	if string(sec2.Data["password"]) != pwBefore {
		t.Errorf("password rotated unexpectedly: before=%q after=%q", pwBefore, sec2.Data["password"])
	}
}

// TestReconcile_BYOSecretPasswordRotation simulates the documented
// rotation flow: the user updates the BYO Secret data (or, equivalently,
// annotates the User CR with pgmqtt.io/rotated-at — the controller
// doesn't read the annotation, only the Secret). The next reconcile
// must compute a new bcrypt hash and update the DB row.
func TestReconcile_BYOSecretPasswordRotation(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	byoSec := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{Name: "rot-creds", Namespace: "mqtt"},
		Data:       map[string][]byte{"password": []byte("v1-password")},
	}
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "rot", Namespace: "mqtt"},
		Spec: pgmqttv1alpha1.UserSpec{
			PasswordSecretRef: &corev1.SecretKeySelector{
				LocalObjectReference: corev1.LocalObjectReference{Name: "rot-creds"},
				Key:                  "password",
			},
		},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user, byoSec).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "rot"}}); err != nil {
			t.Fatalf("reconcile %d: %v", i, err)
		}
	}
	var hashV1 string
	if err := pool.QueryRow(context.Background(),
		`SELECT password_hash FROM users WHERE username='rot'`).Scan(&hashV1); err != nil {
		t.Fatalf("query v1: %v", err)
	}
	if err := bcrypt.CompareHashAndPassword([]byte(hashV1), []byte("v1-password")); err != nil {
		t.Errorf("v1 password mismatch: %v", err)
	}

	// Rotate the BYO secret's password.
	var sec corev1.Secret
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "rot-creds"}, &sec); err != nil {
		t.Fatalf("get byo: %v", err)
	}
	sec.Data["password"] = []byte("v2-password")
	if err := cli.Update(context.Background(), &sec); err != nil {
		t.Fatalf("update byo: %v", err)
	}

	if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "rot"}}); err != nil {
		t.Fatalf("reconcile after rotation: %v", err)
	}
	var hashV2 string
	if err := pool.QueryRow(context.Background(),
		`SELECT password_hash FROM users WHERE username='rot'`).Scan(&hashV2); err != nil {
		t.Fatalf("query v2: %v", err)
	}
	if hashV2 == hashV1 {
		t.Error("expected password_hash to change after rotation")
	}
	if err := bcrypt.CompareHashAndPassword([]byte(hashV2), []byte("v2-password")); err != nil {
		t.Errorf("v2 password mismatch: %v", err)
	}
	// Old password must no longer authenticate.
	if err := bcrypt.CompareHashAndPassword([]byte(hashV2), []byte("v1-password")); err == nil {
		t.Error("v1 password still verifies against rotated hash")
	}
}

// TestReconcile_UpdateRequeuesOnFinalizerAddFailure exercises the
// transient-failure path on the finalizer-add Update. A failed Update
// must propagate as a non-nil error so controller-runtime requeues.
func TestReconcile_UpdateRequeuesOnFinalizerAddFailure(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "transient", Namespace: "mqtt"},
	}
	base := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	want := errors.New("simulated etcd failure")
	cli := interceptor.NewClient(base, interceptor.Funcs{
		Update: func(ctx context.Context, c client.WithWatch, obj client.Object, opts ...client.UpdateOption) error {
			if _, ok := obj.(*pgmqttv1alpha1.User); ok {
				return want
			}
			return c.Update(ctx, obj, opts...)
		},
	})
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	_, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "transient"}})
	if err == nil {
		t.Fatal("expected error from finalizer-add Update failure")
	}
	if !errors.Is(err, want) {
		t.Errorf("error = %v, want wraps %v", err, want)
	}
}

// TestReconcile_SecretCreateFailure exercises the transient-failure
// path on auto-gen Secret creation. The reconciler must surface the
// error and set Ready=False with reason SecretError.
func TestReconcile_SecretCreateFailure(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{
			Name:       "create-fail",
			Namespace:  "mqtt",
			Finalizers: []string{"pgmqtt.io/user"},
		},
	}
	base := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	want := errors.New("etcd write quota")
	cli := interceptor.NewClient(base, interceptor.Funcs{
		Create: func(ctx context.Context, c client.WithWatch, obj client.Object, opts ...client.CreateOption) error {
			if _, ok := obj.(*corev1.Secret); ok {
				return want
			}
			return c.Create(ctx, obj, opts...)
		},
	})
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	_, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "create-fail"}})
	if err == nil {
		t.Fatal("expected error from Secret create failure")
	}
	if !errors.Is(err, want) {
		t.Errorf("error = %v, want wraps %v", err, want)
	}
	var got pgmqttv1alpha1.User
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "create-fail"}, &got); err != nil {
		t.Fatalf("get user: %v", err)
	}
	if !hasReadyCondition(got, metav1.ConditionFalse, "SecretError") {
		t.Errorf("expected Ready=False with reason SecretError, got conditions: %+v", got.Status.Conditions)
	}
}

// TestReconcile_DBExecFailureSetsDBErrorCondition exercises the
// transient-failure path on the users INSERT/UPDATE. The reconciler
// must surface the error and set Ready=False with reason DBError.
func TestReconcile_DBExecFailureSetsDBErrorCondition(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	// Drop the users table to make Pool.Exec fail with a known error.
	if _, err := pool.Exec(context.Background(), `DROP TABLE users`); err != nil {
		t.Fatalf("drop users: %v", err)
	}
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{
			Name:       "db-broken",
			Namespace:  "mqtt",
			Finalizers: []string{"pgmqtt.io/user"},
		},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	_, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "db-broken"}})
	if err == nil {
		t.Fatal("expected error when users table is missing")
	}
	var got pgmqttv1alpha1.User
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "db-broken"}, &got); err != nil {
		t.Fatalf("get user: %v", err)
	}
	if !hasReadyCondition(got, metav1.ConditionFalse, "DBError") {
		t.Errorf("expected Ready=False with reason DBError, got conditions: %+v", got.Status.Conditions)
	}
}

// TestReconcile_DeletionDBExecFailure exercises the transient-failure
// path in reconcileDelete. The DB DELETE must surface as an error and
// the finalizer must remain on the User so a retry has another shot.
func TestReconcile_DeletionDBExecFailure(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{
			Name:       "del-broken",
			Namespace:  "mqtt",
			Finalizers: []string{"pgmqtt.io/user"},
		},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	// Trigger Delete to set DeletionTimestamp; finalizer keeps the object.
	if err := cli.Delete(context.Background(), user); err != nil {
		t.Fatalf("delete: %v", err)
	}
	// Drop the users table to force the DB exec to fail.
	if _, err := pool.Exec(context.Background(), `DROP TABLE users`); err != nil {
		t.Fatalf("drop users: %v", err)
	}
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "del-broken"}}); err == nil {
		t.Fatal("expected error from DELETE on missing users table")
	}
	// Finalizer must still be present so K8s won't reap the User.
	var got pgmqttv1alpha1.User
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "del-broken"}, &got); err != nil {
		t.Fatalf("get user: %v", err)
	}
	found := false
	for _, f := range got.Finalizers {
		if f == "pgmqtt.io/user" {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("finalizer prematurely removed despite DB failure: %+v", got.Finalizers)
	}
}

// TestReconcile_DeletionWithoutFinalizerNoOp exercises the early
// return in reconcileDelete when our finalizer was somehow already
// removed (e.g. force-deleted user) but a stray event still triggers
// reconcile. The reconciler must not touch the DB and must not error.
//
// We seed the object with only a sentinel finalizer (NOT the operator's)
// and call cli.Delete to set the DeletionTimestamp — because the
// sentinel finalizer keeps the object visible, this exercises the
// reconcileDelete entry path while ContainsFinalizer returns false.
func TestReconcile_DeletionWithoutFinalizerNoOp(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	// Pre-seed a user row in the DB so we can verify it isn't deleted.
	if _, err := pool.Exec(context.Background(),
		`INSERT INTO users(username, password_hash) VALUES('untouched', 'whatever')`); err != nil {
		t.Fatalf("seed: %v", err)
	}
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{
			Name:       "untouched",
			Namespace:  "mqtt",
			Finalizers: []string{"some.other.controller/keepalive"},
		},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	// Now delete to set DeletionTimestamp; sentinel finalizer keeps it visible.
	if err := cli.Delete(context.Background(), user); err != nil {
		t.Fatalf("delete: %v", err)
	}
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	res, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "untouched"}})
	if err != nil {
		t.Fatalf("reconcile: %v", err)
	}
	if res.Requeue {
		t.Errorf("unexpected requeue: %+v", res)
	}
	// Row must still be present.
	var n int
	if err := pool.QueryRow(context.Background(),
		`SELECT count(*) FROM users WHERE username='untouched'`).Scan(&n); err != nil {
		t.Fatalf("query: %v", err)
	}
	if n != 1 {
		t.Errorf("user row touched despite missing finalizer: %d rows", n)
	}
}

// TestReconcile_BcryptCostInvalid exercises the validation boundary
// where r.BcryptCost is below bcrypt.MinCost (>0 — cost=0 is treated
// as DefaultCost). bcrypt.GenerateFromPassword returns InvalidCostError;
// the reconciler must wrap it as "bcrypt: ..." and propagate.
func TestReconcile_BcryptCostInvalid(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{
			Name:       "bad-cost",
			Namespace:  "mqtt",
			Finalizers: []string{"pgmqtt.io/user"},
		},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
		BcryptCost: 32, // > bcrypt.MaxCost (31) — InvalidCostError
	}
	_, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "bad-cost"}})
	if err == nil {
		t.Fatal("expected error for cost > bcrypt.MaxCost")
	}
	if !strings.Contains(err.Error(), "bcrypt:") {
		t.Errorf("expected wrapped bcrypt error, got: %v", err)
	}
}

// TestReconcile_BcryptCostZeroFallsBackToDefault verifies the
// boundary where BcryptCost == 0 falls back to bcrypt.DefaultCost (10).
// This is the implicit-default path most operators will hit.
func TestReconcile_BcryptCostZeroFallsBackToDefault(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "zero-cost", Namespace: "mqtt"},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
		// BcryptCost intentionally left at 0.
	}
	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "zero-cost"}}); err != nil {
			t.Fatalf("reconcile %d: %v", i, err)
		}
	}
	var hash string
	if err := pool.QueryRow(context.Background(),
		`SELECT password_hash FROM users WHERE username='zero-cost'`).Scan(&hash); err != nil {
		t.Fatalf("query: %v", err)
	}
	// bcrypt.DefaultCost = 10 → "$2a$10$..."
	if !strings.HasPrefix(hash, "$2a$10$") {
		t.Errorf("expected default cost 10, got prefix %q", hash[:7])
	}
}

// TestReconcile_SpecUsernameDefaultsToObjectName verifies the
// fallback when spec.Username is empty: the controller uses
// metadata.name as the MQTT username.
func TestReconcile_SpecUsernameDefaultsToObjectName(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "metaonly", Namespace: "mqtt"},
		// Spec.Username left empty.
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "metaonly"}}); err != nil {
			t.Fatalf("reconcile %d: %v", i, err)
		}
	}
	var n int
	if err := pool.QueryRow(context.Background(),
		`SELECT count(*) FROM users WHERE username='metaonly'`).Scan(&n); err != nil {
		t.Fatalf("query: %v", err)
	}
	if n != 1 {
		t.Errorf("expected 1 user row for username=metaonly, got %d", n)
	}
}

// TestReconcile_GetUserTransientError exercises the error path from
// the initial Get when the API returns something other than NotFound.
// The reconciler must propagate the error so controller-runtime backs
// off and retries.
func TestReconcile_GetUserTransientError(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	want := errors.New("api server unreachable")
	base := fake.NewClientBuilder().WithScheme(scheme).
		WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	cli := interceptor.NewClient(base, interceptor.Funcs{
		Get: func(ctx context.Context, c client.WithWatch, key client.ObjectKey, obj client.Object, opts ...client.GetOption) error {
			if _, ok := obj.(*pgmqttv1alpha1.User); ok {
				return want
			}
			return c.Get(ctx, key, obj, opts...)
		},
	})
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	_, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "anything"}})
	if !errors.Is(err, want) {
		t.Errorf("expected wrapped %v, got %v", want, err)
	}
}

// TestReconcile_TwoUsersSeparateSecrets verifies the per-User Secret
// naming convention prevents collisions when two User CRs coexist in
// the same namespace. Each User must get its own Secret named
// `<user.Name>-mqtt-credentials` and its own DB row.
func TestReconcile_TwoUsersSeparateSecrets(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	a := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "alice", Namespace: "mqtt"},
	}
	b := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "bob", Namespace: "mqtt"},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(a, b).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	for _, name := range []string{"alice", "bob"} {
		for i := 0; i < 2; i++ {
			if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: name}}); err != nil {
				t.Fatalf("reconcile %s %d: %v", name, i, err)
			}
		}
	}
	var aSec, bSec corev1.Secret
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "alice-mqtt-credentials"}, &aSec); err != nil {
		t.Fatalf("get alice secret: %v", err)
	}
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "bob-mqtt-credentials"}, &bSec); err != nil {
		t.Fatalf("get bob secret: %v", err)
	}
	if string(aSec.Data["username"]) != "alice" || string(bSec.Data["username"]) != "bob" {
		t.Errorf("usernames wrong: alice=%q bob=%q",
			aSec.Data["username"], bSec.Data["username"])
	}
	// Passwords must be independently generated, not shared.
	if string(aSec.Data["password"]) == string(bSec.Data["password"]) {
		t.Error("alice and bob got the same password — independent randomness expected")
	}
	// Both rows in DB.
	var n int
	if err := pool.QueryRow(context.Background(),
		`SELECT count(*) FROM users WHERE username IN ('alice', 'bob')`).Scan(&n); err != nil {
		t.Fatalf("query: %v", err)
	}
	if n != 2 {
		t.Errorf("expected 2 db rows, got %d", n)
	}
}

// TestReconcile_OwnerRefOnAutoGenSecret confirms the OwnerReference
// is set correctly for K8s garbage-collection on User deletion. We
// don't test the GC itself (that's the K8s control plane), only the
// owner ref encoding the reconciler is responsible for.
func TestReconcile_OwnerRefOnAutoGenSecret(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "owns", Namespace: "mqtt", UID: "u-1"},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "owns"}}); err != nil {
			t.Fatalf("reconcile %d: %v", i, err)
		}
	}
	var sec corev1.Secret
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "owns-mqtt-credentials"}, &sec); err != nil {
		t.Fatalf("get secret: %v", err)
	}
	if len(sec.OwnerReferences) != 1 {
		t.Fatalf("expected 1 owner ref, got %d: %+v", len(sec.OwnerReferences), sec.OwnerReferences)
	}
	or := sec.OwnerReferences[0]
	if or.Name != "owns" || or.UID != "u-1" {
		t.Errorf("owner ref name/uid wrong: %+v", or)
	}
	if or.Controller == nil || !*or.Controller {
		t.Errorf("owner ref must be controller=true: %+v", or)
	}
	if or.BlockOwnerDeletion == nil || !*or.BlockOwnerDeletion {
		t.Errorf("owner ref must block-owner-deletion: %+v", or)
	}
	// Schema GVK on the owner ref should resolve to the User CR.
	gvk := schema.GroupVersionKind{Group: "pgmqtt.io", Version: "v1alpha1", Kind: "User"}
	if or.APIVersion != gvk.GroupVersion().String() || or.Kind != gvk.Kind {
		t.Errorf("owner ref GVK wrong: %s/%s vs %s/%s", or.APIVersion, or.Kind, gvk.GroupVersion(), gvk.Kind)
	}
}

// TestReconcile_AutoGenSecretExistsWithoutPasswordKey exercises the
// edge case where the auto-generated Secret name is occupied by a
// pre-existing Secret that lacks the "password" key. The reconciler
// must fall through to generating a fresh password rather than
// stalling with empty-string credentials.
func TestReconcile_AutoGenSecretExistsWithoutPasswordKey(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "nokey", Namespace: "mqtt"},
	}
	preexisting := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "nokey-mqtt-credentials",
			Namespace: "mqtt",
		},
		Data: map[string][]byte{"some-other-key": []byte("ignored")},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user, preexisting).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "nokey"}}); err != nil {
			t.Fatalf("reconcile %d: %v", i, err)
		}
	}
	var sec corev1.Secret
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "nokey-mqtt-credentials"}, &sec); err != nil {
		t.Fatalf("get secret: %v", err)
	}
	if len(sec.Data["password"]) == 0 {
		t.Error("password not generated when pre-existing secret lacked password key")
	}
}

// TestReconcile_AutoGenSecretGetTransientError exercises the
// pass-through branch where Get on the auto-generated Secret name
// returns a non-NotFound error (e.g. API connectivity blip). The
// reconciler must propagate the error so a retry occurs.
func TestReconcile_AutoGenSecretGetTransientError(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)
	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{
			Name:       "get-fail",
			Namespace:  "mqtt",
			Finalizers: []string{"pgmqtt.io/user"},
		},
	}
	base := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()
	want := errors.New("api server flake")
	cli := interceptor.NewClient(base, interceptor.Funcs{
		Get: func(ctx context.Context, c client.WithWatch, key client.ObjectKey, obj client.Object, opts ...client.GetOption) error {
			// Only fail Secret Gets; let User Gets through so we
			// reach the resolveCredentialSecret branch.
			if _, ok := obj.(*corev1.Secret); ok {
				return want
			}
			return c.Get(ctx, key, obj, opts...)
		},
	})
	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	_, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "get-fail"}})
	if err == nil {
		t.Fatal("expected error from Secret Get failure")
	}
	if !errors.Is(err, want) {
		t.Errorf("error = %v, want wraps %v", err, want)
	}
	var got pgmqttv1alpha1.User
	if err := base.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "get-fail"}, &got); err != nil {
		t.Fatalf("get user via base: %v", err)
	}
	if !hasReadyCondition(got, metav1.ConditionFalse, "SecretError") {
		t.Errorf("expected Ready=False with reason SecretError, got conditions: %+v", got.Status.Conditions)
	}
}

// TestUserReconcileLeaseHandoffPasswordRace exercises the lease-handoff
// race where two managers both think they hold the operator Lease and
// both reconcile the same User CR concurrently. The dangerous interleave:
//
//	t0 A.Get(secret) → NotFound; A generates password_A
//	t0 B.Get(secret) → NotFound; B generates password_B
//	t1 A bcrypt(A) → DB.UPSERT
//	t2 B bcrypt(B) → DB.UPSERT          (DB now has bcrypt(B))
//	t3 B Create(secret) with B          (Secret has B)
//	t4 A's CreateOrUpdate retries: Get sees B → MutateFn overwrites with A
//	    → final Secret has A
//	   final state: Secret=A, DB=bcrypt(B). Auth fails forever.
//
// The fix re-orders Reconcile so each manager runs Secret CreateOrUpdate
// FIRST (with a MutateFn that preserves any pre-existing data["password"]
// rather than always overwriting), then re-Gets the merged Secret to read
// the password that won the K8s API race, and finally bcrypts THAT before
// writing PG. The post-condition is the system invariant:
//
//	bcrypt(secret.Data["password"]) verifies against the DB password_hash.
//
// We drive two reconciles in sequence: R_A goes first and creates the
// Secret. We then simulate "peer manager B reached the K8s API faster
// than R_A's view" by directly mutating the Secret's data["password"]
// to a fresh value via the underlying client, then clear the User CR's
// observed-secret-hash to force R_A through the non-short-circuit path.
// R_A's next Reconcile must:
//   - preserve the peer-set password (NOT overwrite with a fresh random),
//   - re-Get to observe that password,
//   - bcrypt THAT password into PG.
//
// The assertion checks the invariant holds after each reconcile, which
// would have been violated by the OLD bcrypt-then-CreateOrUpdate ordering.
func TestUserReconcileLeaseHandoffPasswordRace(t *testing.T) {
	t.Parallel()
	pool := dbtest.FreshPool(t)
	scheme := newScheme(t)

	user := &pgmqttv1alpha1.User{
		ObjectMeta: metav1.ObjectMeta{Name: "ha", Namespace: "mqtt"},
	}
	cli := fake.NewClientBuilder().WithScheme(scheme).
		WithObjects(user).
		WithStatusSubresource(&pgmqttv1alpha1.User{}).Build()

	r := &operator.UserReconciler{
		Client: cli, Scheme: scheme, Pool: pool,
		Logger:      slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})),
		ServiceHost: "pgmqtt", ServicePort: 1883, WSPort: 8083,
	}
	// First pass adds the finalizer; second pass provisions the Secret + DB.
	for i := 0; i < 2; i++ {
		if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "ha"}}); err != nil {
			t.Fatalf("reconcile %d: %v", i, err)
		}
	}
	assertSecretMatchesDB(t, cli, pool, "mqtt", "ha-mqtt-credentials", "ha")

	// Simulate peer manager B writing a different password into the
	// Secret during the lease-handoff window — modelling B's
	// CreateOrUpdate landing AFTER R_A's previous CreateOrUpdate but
	// BEFORE R_A's next reconcile sees the system. R_A must adopt the
	// peer's value (NOT overwrite it with a fresh random) and bcrypt
	// it into the DB so Secret and PG converge.
	var sec corev1.Secret
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "ha-mqtt-credentials"}, &sec); err != nil {
		t.Fatalf("get secret: %v", err)
	}
	sec.Data["password"] = []byte("PEER-WROTE-LAST")
	if err := cli.Update(context.Background(), &sec); err != nil {
		t.Fatalf("simulate peer write: %v", err)
	}
	// Bypass the ObservedSecretHash short-circuit so reconcile re-runs
	// the bcrypt+PG path.
	var u pgmqttv1alpha1.User
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "ha"}, &u); err != nil {
		t.Fatalf("get user: %v", err)
	}
	u.Status.ObservedSecretHash = ""
	u.Status.CredentialsSecretRef = nil
	if err := cli.Status().Update(context.Background(), &u); err != nil {
		t.Fatalf("clear status: %v", err)
	}

	// R_A reconciles after the peer-write. With the fix's MutateFn
	// preserving existing passwords, the peer's value must persist;
	// without the re-Get-then-bcrypt ordering, the DB hash could lag
	// behind. The post-condition is the invariant.
	if _, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: types.NamespacedName{Namespace: "mqtt", Name: "ha"}}); err != nil {
		t.Fatalf("reconcile post-peer-write: %v", err)
	}
	assertSecretMatchesDB(t, cli, pool, "mqtt", "ha-mqtt-credentials", "ha")
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: "mqtt", Name: "ha-mqtt-credentials"}, &sec); err != nil {
		t.Fatalf("get secret post-reconcile: %v", err)
	}
	if string(sec.Data["password"]) != "PEER-WROTE-LAST" {
		t.Errorf("peer-set password was overwritten: got %q, want %q",
			sec.Data["password"], "PEER-WROTE-LAST")
	}
}

// assertSecretMatchesDB asserts the User's PG password_hash bcrypt-verifies
// against the credentials Secret's data["password"]. This is the system
// invariant the lease-handoff fix protects.
func assertSecretMatchesDB(t *testing.T, cli client.Client, pool *pgxpool.Pool, namespace, secretName, username string) {
	t.Helper()
	var sec corev1.Secret
	if err := cli.Get(context.Background(), types.NamespacedName{Namespace: namespace, Name: secretName}, &sec); err != nil {
		t.Fatalf("get secret: %v", err)
	}
	var hash string
	if err := pool.QueryRow(context.Background(),
		`SELECT password_hash FROM users WHERE username=$1`, username).Scan(&hash); err != nil {
		t.Fatalf("query users: %v", err)
	}
	if err := bcrypt.CompareHashAndPassword([]byte(hash), sec.Data["password"]); err != nil {
		t.Errorf("invariant violated: bcrypt(secret.password) does not verify DB hash: %v\n  secret.password=%q\n  hash=%q",
			err, sec.Data["password"], hash)
	}
}

// hasReadyCondition returns true if the User has a Ready condition
// matching the given status and reason.
func hasReadyCondition(u pgmqttv1alpha1.User, status metav1.ConditionStatus, reason string) bool {
	for _, c := range u.Status.Conditions {
		if c.Type == "Ready" && c.Status == status && c.Reason == reason {
			return true
		}
	}
	return false
}
