{{- if and .Values.serviceMonitor.enabled .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pgmqtt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgmqtt.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pgmqtt.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
{{- end }}
